src/input-item/demo/index.axml
src/input-item/index.acss
src/list/demo/app.axml
src/list/demo/index.js
src/list/index.md
src/list/list-item/index.acss
src/list/list-item/index.axml
src/list/list-item/index.js
src/modal/index.acss

fix: 修复组件样式问题

---

src/app.json
src/list/demo/app.js
src/steps/demo/index.acss
src/steps/demo/index.axml
src/steps/demo/index.js
src/steps/demo/index.json
src/steps/index.acss
src/steps/index.axml
src/steps/index.js
src/steps/index.json
src/steps/index.md

feature: add components steps

---

src/steps/demo/index.axml
src/steps/demo/index.js
src/steps/index.acss
src/steps/index.axml
src/steps/index.md

fix: steps style fixed

---

src/grid/demo/2/index.axml
src/grid/demo/2/index.js
src/grid/demo/3/index.axml
src/grid/demo/3/index.js
src/grid/index.acss
src/grid/index.axml
src/grid/index.js
src/input-item/demo/index.axml
src/input-item/index.acss
src/list/index.acss
src/list/list-item/index.acss
src/modal/demo/index.axml
src/modal/index.acss
src/modal/index.axml
src/modal/index.js
src/modal/index.md

fix: fix UI

---

src/app.json
src/list/demo/app.js
src/popover/demo/index.acss
src/popover/demo/index.axml
src/popover/demo/index.js
src/popover/demo/index.json
src/popover/index.acss
src/popover/index.axml
src/popover/index.js
src/popover/index.json
src/popover/index.md
src/popover/popover-item/index.acss
src/popover/popover-item/index.axml
src/popover/popover-item/index.js
src/popover/popover-item/index.json
src/steps/demo/index.axml
src/steps/index.acss
src/steps/index.axml

Feature components popover & fixed components steps bug

---

src/amount-input/demo/index.axml
src/amount-input/demo/index.js
src/amount-input/demo/index.json
src/amount-input/index.acss
src/amount-input/index.axml
src/amount-input/index.js
src/amount-input/index.json
src/amount-input/index.md
src/app.json
src/filter/index.md
src/list/demo/app.js
src/search-bar/index.md

feat: amount-input

---

src/amount-input/demo/index.axml
src/amount-input/demo/index.js
src/amount-input/index.axml
src/amount-input/index.js

- amount-input support onFocus & onBlur

feat: amount-input support onFocus & onBlur

---

CHANGELOG.md
package.json

bump 0.1.0

---

README.md

docs: remove wrong link

---

src/swipe-action/demo/index.axml
src/swipe-action/demo/index.js
src/swipe-action/index.js
src/swipe-action/index.md

enhance swipe-action fix #16

---

src/tabs/demo/index.axml
src/tabs/index.acss
src/tabs/index.axml
src/tabs/index.js
src/tabs/index.md

- enhance tabs swipeable fix #15

feat: enhance tabs swipeable fix #15

---

src/swipe-action/index.axml

优化 swipe-action 的动画性能

---

src/tabs/index.axml

fix: anmation translateX

---

src/swipe-action/demo/index.axml
src/swipe-action/demo/index.js
src/swipe-action/index.js
src/swipe-action/index.md

通过props传入holdSwipe可能比较麻烦，我把holdSwipe改成了data，然后暴露done方法来合上

holdSwipe改成调用done()合上

---

src/tabs/index.axml

fix: fix tabs flicker

---

src/app.json
src/list/demo/app.js
src/vtabs/demo/index.axml
src/vtabs/demo/index.js
src/vtabs/demo/index.json
src/vtabs/index.acss
src/vtabs/index.axml
src/vtabs/index.js
src/vtabs/index.json
src/vtabs/index.md
src/vtabs/vtab-content/index.axml
src/vtabs/vtab-content/index.js
src/vtabs/vtab-content/index.json

feat: vtab component

---

src/swipe-action/index.axml
src/swipe-action/index.js

优化swipe-action fix #35

---

src/app.json
src/face-detection/demo/index.acss
src/face-detection/demo/index.axml
src/face-detection/demo/index.js
src/face-detection/demo/index.json
src/face-detection/index.axml
src/face-detection/index.js
src/face-detection/index.json
src/face-detection/index.md
src/list/demo/app.js

feat: face-detection component

---

src/swipe-action/demo/index.js
src/swipe-action/index.acss
src/swipe-action/index.axml
src/swipe-action/index.js

feat: fix swipe-action rightBtn width

---

src/face-detection/demo/index.axml
src/face-detection/demo/index.js
src/face-detection/index.js
src/face-detection/index.md

feat: optimize face-detection API name

---

src/calendar/index.axml

fix: fix calendar flicker

---

src/app.json
src/footer/demo/index.axml
src/footer/demo/index.js
src/footer/demo/index.json
src/footer/index.acss
src/footer/index.axml
src/footer/index.js
src/footer/index.json
src/list/demo/app.js

feat: footer component

---

CHANGELOG.md
package.json

- **Feature**
- 新增`face-detection`组件
- 新增`footer`组件
- `page-result`组件增加slot，方便开发者个性化定制区域内容
- 优化`calendar`组件在初次渲染时的闪烁问题
- 优化`swipe-action`右侧按钮宽度自适应文本内容

bump 0.3.0

---

src/face-detection/demo/index.axml
src/face-detection/index.axml
src/face-detection/index.js
src/face-detection/index.md

- face-detection新增appName和serviceName接口

feat: face-detection新增appName和serviceName接口

---

CHANGELOG.md
package.json

- `face-detection`组件新增`appName`和`serviceName`字段

bump 0.3.1

---

src/face-detection/demo/index.js
src/face-detection/index.js
src/face-detection/index.md

docs: 更新face-detection组件文档

---

src/app.json
src/list/demo/app.js
src/popup/demo/index.acss
src/popup/demo/index.axml
src/popup/demo/index.js
src/popup/demo/index.json
src/popup/index.acss
src/popup/index.axml
src/popup/index.js
src/popup/index.json
src/popup/index.md

feat: popup弹出菜单

---

src/tabs/index.axml

fix: tabs initial tabWidth

---

src/tabs/demo/index.acss
src/tabs/demo/index.axml
src/tabs/index.acss
src/tabs/index.axml
src/tabs/index.js
src/tabs/tab-content/index.acss
src/tabs/tab-content/index.axml
src/tabs/util.sjs

fix: height auto

---

src/face-detection/demo/index.axml
src/face-detection/demo/index.js
src/face-detection/index.js
src/face-detection/index.md

- feat: face-detection support miniRotate

feat: face-detection support miniRotate

---

src/search-bar/index.acss
src/search-bar/index.axml

- fix: 修复search-bar点击清除icon无效问题

Fix searchbar

---

src/list/list-item/index.acss

feat: 列表样式优化

---

CHANGELOG.md
package.json

- **Bug Fix**
- 修复`search-bar`点击icon无效的bug
- 修复`search-bar`苹果输入法中间态无法清除placeholder的bug
- 优化`list`组件样式

bump 0.3.5

---

src/swipe-action/demo/index.js

fix(swipe-action): 修改demo 0判断问题

---

src/search-bar/index.js
src/tips/demo/1/index.acss
src/tips/demo/1/index.axml
src/tips/demo/1/index.js
src/tips/index.md
src/tips/tips-dialog/index.acss
src/tips/tips-dialog/index.axml
src/tips/tips-dialog/index.js

Fix dialog

---

src/vtabs/demo/index.axml
src/vtabs/demo/index.js
src/vtabs/index.js

新增两个回调函数：
onTabClick
onScrollBar
可运行看下Demo中的效果

新增监听vtabs组件左侧点击和右侧滑动切换分类的回调

---

src/popup/index.axml
src/popup/index.js
src/popup/index.md

feat: popup新增disableScroll属性

---

src/swipe-action/demo/index.axml
src/swipe-action/demo/index.js
src/swipe-action/index.md

feat: 完善swipe-action的demo

---

src/input-item/demo/index.axml
src/input-item/index.js

- 修复input-item event无dataset的bug

fix: fix #66

---

src/swipe-action/index.md

doc: update swipe-action doc

---

src/input-item/demo/index.axml
src/input-item/demo/index.js
src/input-item/index.js

fix: input-item clear示例完善

---

src/list/index.md

doc: update list doc

---

CHANGELOG.md
package.json
src/list/index.md
src/tabs/index.md

- **Bug Fix**
- 修复了input-item组件在失去焦点等事件中无dataset的问题([#66](https://github.com/ant-mini-program/mini-antui/issues/66))
- 修复popup组件mask定位为absolut导致的页面滚动时mask跟着滚动的bug
- popup新增disableScroll属性以适应不同业务场景
- 完善swipe-action的示例代码
- 文档更新，添加体验二维码

bump 0.3.7

---

src/app.json
src/input-item/demo/index.acss
src/input-item/demo/index.axml
src/input-item/demo/index.js
src/input-item/demo/index.json
src/input-item/index.acss
src/input-item/index.axml
src/input-item/index.js
src/input-item/index.md
src/list/demo/app.js
src/picker-item/demo/index.acss
src/picker-item/demo/index.axml
src/picker-item/demo/index.js
src/picker-item/demo/index.json
src/picker-item/index.acss
src/picker-item/index.axml
src/picker-item/index.js
src/picker-item/index.json
src/picker-item/index.md

- 新增picker-item & input-item信息clear功能

feat: 新增picker-item & input-item信息clear功能

---

src/filter/demo/single/index.js
src/filter/filter-item/index.js
src/filter/index.axml
src/filter/index.js

fix: 修复filter组件单选时要反选的bug

---

src/list/demo/index.axml
src/list/index.md
src/list/list-item/index.js

fix: list-item点击事件支持dataset fix #85

---

src/picker-item/index.js
src/tabs/index.axml
src/tabs/index.js
src/tabs/index.md

feat: 新增激活tabbar的自定义class fix #87

---

src/input-item/index.axml
src/input-item/index.js

- 修复inputitem获取焦点的时候清除按钮不消失的问题

fix: 修复inputitem获取焦点的时候清除按钮不消失的问题

---

src/input-item/index.acss
src/list/index.acss
src/list/list-item/index.acss
src/picker-item/index.acss

fix: 解决1rpx在安卓下表现为1px的问题

---

src/input-item/index.acss
src/list/list-item/index.acss
src/picker-item/index.acss

fix: 解决list-bottom的底线问题

---

src/input-item/index.acss
src/input-item/index.axml
src/input-item/index.js

fix: input-item兼容input组件同步宽度的问题

---

src/page-result/index.acss

fix: page-result图片升级到最新版本

---

src/input-item/index.js

fix: 兼容因为syncInput导致输入抖动的bug

---

src/stepper/demo/index.js
src/stepper/index.axml
src/stepper/index.js
src/vtabs/index.js

fix: fix #111

---

src/search-bar/index.acss

fix: fix #113

---

src/vtabs/demo/index.js
src/vtabs/index.acss
src/vtabs/index.axml
src/vtabs/index.md

feat: vtab新增badge

---

src/input-item/index.axml
src/input-item/index.js

fix: 兼容native input的输入bug

---

src/swipe-action/demo/index.axml
src/swipe-action/index.md

doc: fix #120

---

src/vtabs/index.js

fix: vtabs didUpdate时没有处理高度的问题

---

src/vtabs/index.js

fix: 解决timerId为null的问题

---

README.md
src/picker-item/index.md

docs: update readme

---

src/tabs/index.acss
src/tabs/index.js

fix: didUpdate计算tabs length

---

src/vtabs/index.js

fix: 修复安卓下高度的误差

---

src/calendar/demo/index.axml
src/calendar/demo/index.js
src/calendar/index.acss
src/calendar/index.axml
src/calendar/index.js
src/calendar/index.md

- 日历新增disable和onSelectHasDisableDate属性

feat: 日历新增disable和onSelectHasDisableDate属性

---

src/tabs/index.js

fix: 兼容scroll-view animation的问题

---

src/app.json
src/badge/demo/index.acss
src/badge/demo/index.axml
src/badge/demo/index.js
src/badge/demo/index.json
src/badge/index.acss
src/badge/index.axml
src/badge/index.js
src/badge/index.json
src/badge/index.md
src/list/demo/app.js
src/tabs/index.acss
src/tabs/index.axml
src/tabs/index.json

Feat badge

---

src/vtabs/demo/index.js
src/vtabs/index.acss
src/vtabs/index.axml
src/vtabs/index.json

feat: vtabs组合使用badge组件

---

src/am-checkbox/index.md
src/badge/index.md

docs: badge和am-checkbox文档新增二维码

---

src/notice/demo/index.acss
src/notice/demo/index.axml
src/notice/demo/index.js
src/notice/index.acss
src/notice/index.axml
src/notice/index.js
src/notice/index.md

feat: notice新增marquee

---

src/message/index.axml

fix: 兼容message为type为fail时的问题

---

CHANGELOG.md
package.json

- `notice`新增`enableMarquee`和`marqueeProps`属性([#140](https://github.com/ant-mini-program/mini-antui/issues/140))
- **Bug Fix**
- 修复`message`type为`fail`时的白屏问题([#152](https://github.com/ant-mini-program/mini-antui/issues/152))

bump 0.4.1

---

src/vtabs/demo/index.axml
src/vtabs/demo/index.js
src/vtabs/index.axml
src/vtabs/index.js
src/vtabs/index.md

- tabs新增activeTab、onTabClick、onChange等属性

feat: vtabs新增activeTab、onTabClick、onChange等属性

---

CHANGELOG.md
package.json

- `amount-input`组件type属性新增`digit`类型
- `vtabs`新增`activeTab`，`onTabClick`和`onChange`属性([#125](https://github.com/ant-mini-program/mini-antui/issues/125))

bump 0.4.2

---

src/tabs/index.axml
src/tabs/index.js
src/tabs/index.md

feat: tabs新增自定义tabbarcls

---

src/tabs/index.axml
src/tabs/index.js
src/tabs/index.md

feat: tabs新增duration来控制滑动时长

---

CHANGELOG.md
package.json

- `tabs`新增`tabBarCls`tabBar自定义样式class
- `tabs`新增`duration`控制滑动动画时长
- `calendar`date参数兼容IOS格式要求

bump 0.4.3

---

src/notice/index.axml
src/notice/index.js

Extend clickable area of link mode of notice to whole component.

feat: extend clickable area of notice.

---

src/popup/index.axml
src/popup/index.md
src/tips/tips-dialog/index.acss

- `popup`新增zIndex属性
- 替换`tips`图片资源

Feat popup zindex

---

src/filter/demo/alternative/index.axml
src/filter/demo/index.axml
src/filter/demo/single/index.axml
src/filter/filter-item/index.js
src/list/list-item/index.acss

feat: replace url with base64

---

src/am-checkbox/index.acss
src/am-checkbox/index.axml
src/am-checkbox/index.js
src/am-checkbox/index.md

feat: checkbox新增size属性

---

src/am-checkbox/index.acss
src/am-checkbox/index.axml
src/am-checkbox/index.js
src/am-checkbox/index.md

This reverts commit 54c23272a892777a7027871c7ae1058afe802168

Revert "feat: checkbox新增size属性 (#174)"

---

package.json
scripts/pub.js

feat: auto tag script

---

src/swipe-action/index.js

Fix swipe action

---

src/stepper/demo/index.axml
src/stepper/index.js

fix: stepper兼容字符串类型

---

CHANGELOG.md
package.json

- `swipe-action`版本判断优化([#176](https://github.com/ant-mini-program/mini-antui/issues/176))
- `stepper`value属性类型兼容字符串

bump 0.4.7

---

src/page-result/index.md

fix: fix doc typo

---

src/steps/demo/index.axml
src/steps/demo/index.js
src/steps/index.acss
src/steps/index.axml
src/steps/index.js
src/steps/index.md

feat: steps add icon url

---

CHANGELOG.md
package.json

- **Feature**
- 新增`flex`、`flex-item`布局组件
- `steps`支持自定义icon
- `amount-input`支持`controlled`属性

bump 0.4.8

---

src/badge/demo/index.js
src/badge/index.acss
src/badge/index.axml

fix issue of vertical align of text within badge

fix: vertical align of text within badge.

---

src/badge/demo/index.js
src/badge/index.acss
src/badge/index.axml

fix: auto width of badge.

---

src/notice/index.acss

fix: operation height issue of notice

fix: operation height issue of notice

---

components/style/themes/default.less

feat: Add less variables

---

components/pagination/index.axml
components/pagination/index.less

feat: pagination component.

---

components/pagination/index.axml

feat: disable pagination button

---

components/popup/index.less

- compatible with inpagerender

fix: compatible with inpagerender

---

README.md

feat: readme add dev rule

---

components/am-checkbox/index.md
components/amount-input/index.md
components/badge/index.md
components/calendar/index.md
components/card/index.md
components/filter/index.md
components/flex/index.md
components/footer/index.md
components/grid/index.md
components/input-item/index.md
components/list/index.md
components/message/index.md
components/modal/index.md
components/notice/index.md
components/page-result/index.md
components/pagination/index.md
components/picker-item/index.md
components/popover/index.md
components/popup/index.md
components/search-bar/index.md
components/stepper/index.md
components/steps/index.md
components/swipe-action/index.md
components/tabs/index.md
components/tips/index.md
components/vtabs/index.md

docs: unify doc style

---

.eslintrc
package.json

chore: Add TSLint config

---

components/notice/index.axml
components/notice/index.less
components/notice/index.ts
components/pagination/index.ts

fix: performance optimization of Notice.

fix: performance optimization of Notice.

---

components/pagination/index.axml
components/pagination/index.sjs
components/pagination/index.ts

fix: props issue of Pagination

fix: props issue of Pagination

---

components/notice/index.ts

fix: props default value of notice

fix: props default value of notice

---

components/notice/index.ts

fix: issue when text is not overflow

fix: issue when text is not overflow

---

components/amount-input/index.axml
components/amount-input/index.less
components/badge/index.less
components/input-item/index.less
components/list/index.less
components/list/list-item/index.less
components/message/index.axml
components/message/index.less
components/modal/index.axml
components/modal/index.less
components/pagination/index.less
components/picker-item/index.less
components/style/mixins/hairline.less

feat: Added 1px less mixin

---

components/badge/index.less

fix: badge style typo

---

components/am-icon/index.md
components/flex/index.md

docs: Added demo qrcode

---

components/am-icon/index.md

docs: list valid icon types

---

components/flex/flex-item/index.less
components/flex/index.less
components/input-item/index.less
components/page-result/index.less
components/picker-item/index.less
components/tabs/index.less
components/vtabs/index.less

chore: rewrite style with less

---

components/vtabs/index.axml
components/vtabs/index.ts

fix: vtabs unique id

---

components/collapse/collapse-item/index.axml
components/collapse/index.axml

fix: collapse axml template stings

---

components/input-item/index.ts
components/picker-item/index.less
components/picker-item/index.ts

fix: picker-item text overflow

---

components/grid/index.axml
components/grid/index.less
examples/pages/filter/single/index.acss
examples/pages/grid/2/index.axml

feat: grid support slot

---

components/calendar/index.less
components/filter/filter-item/index.less
components/filter/index.less
components/tips/tips-dialog/index.less
components/tips/tips-plain/index.less

chore: less rewrite about calendar、filter、tips

chore: less rewrite about calendar、filter、tips

---

components/collapse/collapse-item/index.axml
components/collapse/collapse-item/index.json
components/collapse/collapse-item/index.less
components/notice/index.less
components/search-bar/index.less

refactor: rewrite style of search-bar by less

refactor: rewrite style of search-bar by less

---

components/list/list-item/index.ts

fix: list-item sync dataset

---

components/grid/index.md

Add grid component slot document.

Feature grid slot document

---

package.json
scripts/compiler.js
yarn.lock

chore: compile css conditionally

---

components/modal/index.md

docs: fix modal doc typo

---

components/card/index.less
components/footer/index.less
components/list/index.less
components/list/list-item/index.less
components/style/themes/default.less

feat: footer list card less rewrite

---

components/swipe-action/index.less

First of all, thank you for your contribution! :-)
Please makes sure that these checkboxes are checked before submitting your PR, thank you!
Extra checklist:
**if** *isNewFeature* **:**

feat:swipe-action-less

---

components/collapse/index.md

refactor: modify doc of collapse

refactor: modify doc of collapse

---

.eslintignore
.npmrc
tsconfig.json
types/custom.ts
types/index.d.ts

chore: Added ts declaration files

---

components/flex/index.less

flex missed justify-content center #247

fix: flex missed justify-content center #247

---

components/collapse/index.md

docs: update collapse doc

---

components/swipe-action/index.md

docs: complete swipe-action doc

---

components/amount-input/index.less
components/calendar/index.less
components/notice/index.less

feat: default box-sizing style

---

components/modal/index.axml
components/modal/index.md
components/modal/index.ts

modal added disableScroll props

feat: modal added disableScroll props

---

components/badge/index.less

fix: badge text nowrap

---

components/notice/index.md

docs: fix notice doc typo

---

components/am-icon/index.ts

default className prop of am-icon

fix: default className prop of am-icon

---

components/vtabs/index.axml

fix: vtab typo

---

components/list/list-item/index.less

fix: List word-break

---

CHANGELOG.md
package.json

release 0.4.26

---

package.json

chore: specify a license

---

components/collapse/index.ts

instanceof problem in dingtalk

fix: instanceof problem in dingtalk

---

components/vtabs/index.axml

VTab scroll issue when page allowsBounceVertical

fix: VTab scroll issue when page allowsBounceVertical

---

components/vtabs/index.ts

Type assertion on Selector result

fix: Type assertion on Selector result

---

components/swipe-action/index.ts

in swipe-action component, clicking list-item will trigger swipe event when swipe-action is not triggered.

fix swipe-action component item click bug

---

components/tabs/tab-content/index.axml
package.json

First of all, thank you for your contribution! :-)
Please makes sure that these checkboxes are checked before submitting your PR, thank you!
修改兼容错误
Extra checklist:
**if** *isNewFeature* **:**

fix(tabs): correct tabs axml

---

components/am-icon/index.axml
components/am-icon/index.ts

First of all, thank you for your contribution! :-)
Please makes sure that these checkboxes are checked before submitting your PR, thank you!
Extra checklist:
**if** *isNewFeature* **:**

feat(am-icon): aria-hidden 属性透传
